import type { WatchFormData } from './types'

export const sampleWatches: WatchFormData[] = [
  {
    brand: 'Rolex',
    model: 'Submariner Date',
    reference: '126610LN',
    serial: '9B3K7241',
    movement: 'Automatic',
    caseMaterial: 'Oystersteel',
    caseSize: 41,
    purchasePrice: 9150,
    purchaseDate: '2023-06-15',
    seller: 'AD — Tourneau NYC',
    estimatedValue: 13500,
    condition: 'Mint',
    serviceHistory: [],
    boxPapers: true,
    notes: 'Daily wearer. Purchased at retail after 8 months on the waitlist.',
    photos: [],
  },
  {
    brand: 'Omega',
    model: 'Speedmaster Moonwatch',
    reference: '310.30.42.50.01.002',
    serial: 'PIC 88421376',
    movement: 'Manual',
    caseMaterial: 'Stainless Steel',
    caseSize: 42,
    purchasePrice: 6300,
    purchaseDate: '2022-11-20',
    seller: 'Omega Boutique Paris',
    estimatedValue: 5800,
    condition: 'Excellent',
    serviceHistory: [],
    boxPapers: true,
    notes: 'Hesalite crystal. Comes with NATO strap and extra bracelet links.',
    photos: [],
  },
  {
    brand: 'Tudor',
    model: 'Black Bay 58',
    reference: 'M79030N-0001',
    serial: '9280HJ',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseSize: 39,
    purchasePrice: 3700,
    purchaseDate: '2024-01-10',
    seller: 'Chrono24 — WatchVault DE',
    estimatedValue: 3900,
    condition: 'Excellent',
    serviceHistory: [],
    boxPapers: true,
    notes: 'Pre-owned, practically unworn. Great vintage-inspired diver.',
    photos: [],
  },
  {
    brand: 'Grand Seiko',
    model: 'Snowflake',
    reference: 'SBGA211',
    serial: '410902',
    movement: 'Automatic',
    caseMaterial: 'Titanium',
    caseSize: 41,
    purchasePrice: 5800,
    purchaseDate: '2021-09-05',
    seller: 'Topper Jewelers SF',
    estimatedValue: 5200,
    condition: 'Good',
    serviceHistory: [
      { id: 'gs-svc-1', date: '2024-03-12', notes: 'Full service at Grand Seiko service center. Spring Drive recalibrated.' },
    ],
    boxPapers: true,
    notes: 'Spring Drive movement. The dial texture is incredible in person.',
    photos: [],
  },
  {
    brand: 'Cartier',
    model: 'Santos de Cartier',
    reference: 'WSSA0029',
    serial: 'JLX48901',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseSize: 40,
    purchasePrice: 7250,
    purchaseDate: '2023-03-28',
    seller: 'Cartier Boutique London',
    estimatedValue: 7000,
    condition: 'Mint',
    serviceHistory: [],
    boxPapers: true,
    notes: 'Medium size. Comes with both bracelet and leather strap via QuickSwitch.',
    photos: [],
  },
  {
    brand: 'Casio',
    model: 'G-Shock Casioak',
    reference: 'GA-2100-1A1',
    serial: '',
    movement: 'Quartz',
    caseMaterial: 'Carbon Core Guard',
    caseSize: 45,
    purchasePrice: 99,
    purchaseDate: '2022-07-01',
    seller: 'Amazon',
    estimatedValue: 85,
    condition: 'Good',
    serviceHistory: [],
    boxPapers: false,
    notes: 'Beater watch for hiking and travel. Battery replaced once.',
    photos: [],
  },
  {
    brand: 'Jaeger-LeCoultre',
    model: 'Reverso Classic',
    reference: 'Q3858520',
    serial: '2974112',
    movement: 'Manual',
    caseMaterial: 'Stainless Steel',
    caseSize: 40,
    purchasePrice: 8900,
    purchaseDate: '2020-12-25',
    seller: 'Gift — purchased at JLC Boutique Geneva',
    estimatedValue: 9500,
    condition: 'Excellent',
    serviceHistory: [
      { id: 'jlc-svc-1', date: '2023-06-20', notes: 'Crystal polished, movement cleaned. Done at JLC service center Paris.' },
    ],
    boxPapers: true,
    notes: 'Christmas gift. Art Deco masterpiece. Engraved initials on caseback.',
    photos: [],
  },
  {
    brand: 'Seiko',
    model: 'Presage Cocktail Time',
    reference: 'SRPB43',
    serial: '870154',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseSize: 40,
    purchasePrice: 350,
    purchaseDate: '2021-02-14',
    seller: 'Jomashop',
    estimatedValue: 280,
    condition: 'Fair',
    serviceHistory: [],
    boxPapers: false,
    notes: 'Dress watch. Some desk diving marks on the clasp. Beautiful blue sunburst dial.',
    photos: [],
  },
]
