import { FileText, Table } from 'lucide-react'
import { useState } from 'react'
import type { Watch } from '../db/types'

interface Props {
  watches: Watch[]
}

function formatCurrency(val: number | null): string {
  if (val == null) return ''
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format(val)
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function exportCSV(watches: Watch[]) {
  const headers = ['Brand', 'Model', 'Reference', 'Serial', 'Movement', 'Case Material', 'Case Size (mm)', 'Purchase Price', 'Purchase Date', 'Seller', 'Estimated Value', 'Condition', 'Box & Papers', 'Notes']
  const rows = watches.map((w) => [
    w.brand,
    w.model,
    w.reference,
    w.serial,
    w.movement,
    w.caseMaterial,
    w.caseSize?.toString() ?? '',
    w.purchasePrice?.toString() ?? '',
    w.purchaseDate,
    w.seller,
    w.estimatedValue?.toString() ?? '',
    w.condition,
    w.boxPapers ? 'Yes' : 'No',
    w.notes.replace(/"/g, '""'),
  ])

  const csv = [headers, ...rows].map((row) => row.map((c) => `"${c}"`).join(',')).join('\n')
  downloadBlob(new Blob([csv], { type: 'text/csv' }), `watch-collection-${new Date().toISOString().split('T')[0]}.csv`)
}

async function exportPDF(watches: Watch[]) {
  const { default: jsPDF } = await import('jspdf')

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 15
  const contentWidth = pageWidth - margin * 2
  let y = margin

  function checkPage(needed: number) {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage()
      y = margin
    }
  }

  // Title
  doc.setFontSize(22)
  doc.setTextColor(212, 175, 55) // gold
  doc.text('Watch Collection Report', margin, y + 7)
  y += 14

  doc.setFontSize(9)
  doc.setTextColor(136, 136, 136)
  doc.text(`Generated ${new Date().toLocaleDateString()} — ${watches.length} watches`, margin, y)
  y += 10

  // Summary
  const totalCost = watches.reduce((s, w) => s + (w.purchasePrice ?? 0), 0)
  const totalValue = watches.reduce((s, w) => s + (w.estimatedValue ?? 0), 0)

  doc.setFillColor(20, 20, 20)
  doc.roundedRect(margin, y, contentWidth, 18, 2, 2, 'F')
  doc.setFontSize(9)
  doc.setTextColor(136, 136, 136)
  doc.text('Total Cost', margin + 5, y + 6)
  doc.text('Estimated Value', margin + 65, y + 6)
  doc.text('P&L', margin + 130, y + 6)
  doc.setFontSize(12)
  doc.setTextColor(229, 229, 229)
  doc.text(formatCurrency(totalCost), margin + 5, y + 13)
  doc.text(formatCurrency(totalValue), margin + 65, y + 13)
  const pl = totalValue - totalCost
  doc.setTextColor(pl >= 0 ? 34 : 239, pl >= 0 ? 197 : 68, pl >= 0 ? 94 : 68)
  doc.text(`${pl >= 0 ? '+' : ''}${formatCurrency(pl)}`, margin + 130, y + 13)
  y += 25

  // Each watch
  for (const watch of watches) {
    checkPage(50)

    doc.setDrawColor(42, 42, 42)
    doc.setFillColor(20, 20, 20)
    doc.roundedRect(margin, y, contentWidth, 40, 2, 2, 'F')

    doc.setFontSize(8)
    doc.setTextColor(212, 175, 55)
    doc.text(watch.brand.toUpperCase(), margin + 5, y + 6)

    doc.setFontSize(13)
    doc.setTextColor(229, 229, 229)
    doc.text(watch.model, margin + 5, y + 13)

    doc.setFontSize(8)
    doc.setTextColor(136, 136, 136)
    if (watch.reference) doc.text(`Ref. ${watch.reference}`, margin + 5, y + 19)

    const specs = [
      watch.movement,
      watch.caseMaterial,
      watch.caseSize ? `${watch.caseSize}mm` : '',
      watch.condition,
      watch.boxPapers ? 'Box & Papers' : '',
    ].filter(Boolean)
    doc.text(specs.join(' | '), margin + 5, y + 25)

    doc.setFontSize(9)
    doc.setTextColor(229, 229, 229)
    doc.text(`Cost: ${formatCurrency(watch.purchasePrice)}`, margin + 5, y + 33)
    doc.text(`Value: ${formatCurrency(watch.estimatedValue)}`, margin + 65, y + 33)

    if (watch.purchasePrice && watch.estimatedValue) {
      const wPl = ((watch.estimatedValue - watch.purchasePrice) / watch.purchasePrice) * 100
      doc.setTextColor(wPl >= 0 ? 34 : 239, wPl >= 0 ? 197 : 68, wPl >= 0 ? 94 : 68)
      doc.text(`${wPl >= 0 ? '+' : ''}${wPl.toFixed(1)}%`, margin + 130, y + 33)
    }

    y += 45
  }

  // Footer
  checkPage(10)
  doc.setFontSize(7)
  doc.setTextColor(80, 80, 80)
  doc.text('Generated by Watch Logbook — for insurance and personal records', margin, doc.internal.pageSize.getHeight() - 8)

  doc.save(`watch-collection-${new Date().toISOString().split('T')[0]}.pdf`)
}

export default function ExportPanel({ watches }: Props) {
  const [exporting, setExporting] = useState<string | null>(null)

  async function handleExport(type: 'pdf' | 'csv') {
    setExporting(type)
    try {
      if (type === 'pdf') await exportPDF(watches)
      else exportCSV(watches)
    } finally {
      setExporting(null)
    }
  }

  if (watches.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-24 px-4 text-center">
        <p className="text-text-dim text-lg">Add watches to export your collection.</p>
      </div>
    )
  }

  return (
    <div className="max-w-2xl mx-auto p-4 space-y-3">
      <p className="text-text-dim text-sm mb-4">
        Export your collection of {watches.length} watches for insurance or records.
      </p>

      <button
        onClick={() => handleExport('pdf')}
        disabled={exporting !== null}
        className="w-full bg-surface border border-border rounded-xl p-4 flex items-center gap-4 text-left hover:border-gold/40 transition-colors disabled:opacity-50"
      >
        <div className="w-10 h-10 rounded-lg bg-red/10 flex items-center justify-center">
          <FileText size={20} className="text-red" />
        </div>
        <div>
          <p className="text-sm font-medium">PDF Report</p>
          <p className="text-text-dim text-xs">For insurance — includes valuations & specs</p>
        </div>
        {exporting === 'pdf' && <span className="ml-auto text-xs text-text-dim">Generating...</span>}
      </button>

      <button
        onClick={() => handleExport('csv')}
        disabled={exporting !== null}
        className="w-full bg-surface border border-border rounded-xl p-4 flex items-center gap-4 text-left hover:border-gold/40 transition-colors disabled:opacity-50"
      >
        <div className="w-10 h-10 rounded-lg bg-green/10 flex items-center justify-center">
          <Table size={20} className="text-green" />
        </div>
        <div>
          <p className="text-sm font-medium">CSV Spreadsheet</p>
          <p className="text-text-dim text-xs">Open in Excel, Google Sheets, etc.</p>
        </div>
        {exporting === 'csv' && <span className="ml-auto text-xs text-text-dim">Generating...</span>}
      </button>
    </div>
  )
}
